name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

# We could run the test in separate jobs, but then, we would have to
# pass artifacts around, which just increases complexity and not really
# necessary for such a project.
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ray_buster
    - name: Run unit tests
      run: docker run ray_buster bazel test --test_output=all //...
    - name: Run clang-tidy
      run: docker run ray_buster bazel build --config clang-tidy //...
    - name: Check code formatting
      run: docker run ray_buster ./format-check.sh
